services:
  kanban-app:
    build: .
    container_name: easy-kanban
    ports:
      - "3221:3010"
      - "3222:3222"
    environment:
      - NODE_ENV=development
      - DOCKER_ENV=true
      - PORT=3222
      - VITE_API_URL=http://localhost:3222
      # Enable demo mode to show countdown timer for hourly resets (demo environments only)
      - DEMO_ENABLED=true
    volumes:
      - .:/app
      - /app/node_modules
      - kanban-data:/app/server/data
      - kanban-attachments:/app/server/attachments
      - kanban-avatars:/app/server/avatars

    restart: unless-stopped

volumes:
  kanban-data:
    driver: local
  kanban-attachments:
    driver: local
  kanban-avatars:
    driver: local
