apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: easy-kanban

resources:
- namespace.yaml
- configmap.yaml
- redis-deployment.yaml
- app-deployment.yaml
- service.yaml
- ingress.yaml

commonLabels:
  app: easy-kanban
  version: v1.0.0

images:
- name: easy-kanban
  newTag: prod
