apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: easy-kanban-avatars-pvc
  namespace: easy-kanban
  labels:
    app: easy-kanban
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-storage
