apiVersion: v1
kind: PersistentVolume
metadata:
  name: easy-kanban-daniel9-attachments-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: /var/lib/easy-kanban-daniel9-attachments
